# Generated by Django 3.2.9 on 2021-12-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentimental',
        ),
    ]
